
export BASE = helm
export CHART = alertmanager
export NAMESPACE = monitoring
export REPO = prometheus-community
export URL = https://prometheus-community.github.io/helm-charts
export VERSION = 0.18.3

include ../Makefile

seal:
_PHONY: seal
