
export BASE = helm
export CHART = spark
export NAMESPACE = spark
export REPO = bitnami
export URL = https://charts.bitnami.com/bitnami
export VERSION = 6.1.10

include ../Makefile

seal:
_PHONY: seal
