apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgA9QsL9QKqK0QUnLIbe3QwFmcwRqfh+4fcIfnU8ejVOd9oi2wLHIRrR6ICHq0sTpeBhfMvsAN+bhN42hAxEYT9stV/hN2bxVd4MF8x47TTLRP0qZQFxP8XOvGLnby8q00mvKKrNJSkuJbSu2Gg3MLhN+UjezXQQBrikqahlMgszQtIdErUNYePXgBlPxSr1jghjFS8L5hBG/iRo1NH2SYxFFrwx8JqSrkuZceBcE3L0u7q55Y/Y5OmvvUhetgkVUQ7ZcxFLIBxbtUzq2tZL5SUXXYILnJvuFQNx6/qQqsKFUu6Byu8fX5sz+Q5HxWfe8jKzw0EGXf/lNt38GGrUzzImtF+k33zVBmuvKjPnFZgQvEY8e4vYIEb7b7J4dXcLEcYvUsfX+RK0THtjKza+/bvx82HLXQZZ8SkNIgzPW2lifrhyhDDyqMFbw4DLU8UslG/e2InKX5uYYMtTzGFmMRtfwWfYTq57ug/YodOIdEiLIOlPScTei4bcBgfbMeSPg5AqXdhS48w08viaUUjZW5E3spZ2TBPqchvWYi+KBzqP6+pJOWQa+POkJdNFv19CuqRIfS9Jy+QgmiAwozW1l0kMofDlkQD6T0667f6fyA4D8fGhCKEEZw9HdQpAlIITRZWbImreH8AGRT2zEJjEZnhdpPj1Quw/9oIBzsOKrPm/Nu2NWLDD8CfRVBKwxUDzCGzcQsJbnNGusQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: postgresql

