
export BASE = helm
export CHART = grafana
export NAMESPACE = monitoring
export REPO = grafana
export URL = https://grafana.github.io/helm-charts
export VERSION = 6.36.2

include ../Makefile

seal:
_PHONY: seal
