apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - service.yaml
  - deployment.yaml

resources:
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
