apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin4
  namespace: pgadmin
spec:
  encryptedData:
    password: AgBG9CIJI4jC8TH7E+lVpF7Fq0NqVwfJyrQHNXn72etCNkuMBpxfVGB5p6dDTBnbZQyLwJJH5oVUfoWFY772Y4qjvX5KnzJM3zVqBhOFy72PM8znplShSaA+0+LBAubh9dgJRkxlJQew60SHBDjS31iDmbqD5akCtnwOZ0Ql77jIJB4EKPHOJOl5I+2lx2wfwJzwdvqSIyvc4x5sPtvkvstUmbh+jMySLHaLhQrQ0jzWBwUWfEyArZmHBJwjK0bfGOekQkWeEBXTREOuAIYQhzz+KLZ8PP4q+hP17bWQZUlKSuA7J00eKZbnCXe2j2pIJipwNsmTd5buHP9L4glcgT0R0dLbcmXYWk/lKJTQUyhp8LPoc0Er8M90XHx9SdRe5QFYw1J3ZvqHTlR9PiPTEiV1DQSYQTxzQFZo0gh2DpfKEBaH500hLjl4gnDS93sWeV+RRp6gAhqtL9ilM4/M+faeIOjelhYCK5786Zxg8ElbnX5LJxuDRRtX0lGzs94nFSHuhJG0MMaLa79tUL1BGQPI4PCYHiu9euZdbTNfnSDwLwyPO37hlg9ncYSoPlMNRagqGIbj5+JXgyPhhXROFz7XowM21iCoJd202bhcDQaSNxH99fJTZfCiT5T4tz+ZcJPB1Y/cLd0im7pm1G/IsQIQ7ygowvHIkkzqksrtYRx74Sbt1UHssjk/7ArcwX1DPAdP+xFiMXyQHw==
    servers.json: AgBmvsLVS1g0iVTX7lYitNl93gLzI89UixMtIDtvuOtiY/ZXeaR+uiggklODvN2o6usqamQCkrmj1XEOqzDBSpoBKsQfCZDZ1fZwFAag8jpIXWXiKAZ0PZnT2jWwd/FJ9/rVzR/j9bW8uIIDjfkQOGHG3wn3zqYy78bj1QNdtoJ2wJfAct5ygL4EEjoto3cHX+EpSYsG6FqOxKR8Snf4wpVR2K6NoI8AWpMIENyoVg1Dsp4YvNdzFTf72oPGJe4R5QndksAKryUUp/kUA1tIdl62pIk9eSFOmO0YH4D4DgW4JvlxRpwHzi6fB11UUB9rStP0m6E1KtfDkWUvpAUaGdPaqjQxNdyMMcmw+hDh7W6DmBvZJKirIsfSdDCC9571e0QGIqB83yXFFTASIiFscH0iZtj6sO3XsEQpJP0Au/XHCu7uS7Sm/0uZ95jfJ09dVgQHLA1VOD2ofh4mXbhcm8tLWAWunHTACm+Hpp2oSvKTFKSB781qdIDZONbDboGb2ThrXr19/17YVUKdEGumrtBMn6TyUUEuIEuq2ARF+X7XGsF7qIe2ifdmshaCM9UroFVOIrBmQGe2YATTwJj4/lquVAIbV3h0E6FRPedL7qyQs3747Qz1kR54PGZ91hlW5A+yvY7qO22hWNwnMgcYeMpi/KYH2YK5PHCVLWNQVpmVrcVZhLQDpvvt2BjcdXtw7MyklUV8nSqSQ5r+lx0AjKutXfj329sg6z6Bju6CEVxGzjwGFXsQwmnBFkY9TAugERmwcHbtjvikEoYHj8vOQZ4GuSyhl4XI7HFQMGW7D52jqw0aW4d2hNfOKhWmWv/+vggqNS+oTNafLgrmw+O8G1ZUQcVDXJq1MZ49+9TNkrUvcZBiLXLCl9j+zP4e3cxpCrN9gsYyGAY3L7OgAXXlxtHywbxw5MLBeClQ8dotq7ikhJVZPyPJv6U6fvjIaMzNhOkPEECkbnHlZskL/hsunnQYZPrl6FF3K1IXF/0F9SFRJg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pgadmin4
      namespace: pgadmin

