
export BASE = helm
export CHART = airflow
export NAMESPACE = airflow
export REPO = apache-airflow
export URL = https://airflow.apache.org
export VERSION = 1.6.0

include ../Makefile

seal:
_PHONY: seal
