# opsbots cluster issuer uses our custom certificate authority to 
# create self signed certificates for our development cluster
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: opsbots
spec:
  ca:
    secretName: opsbots-tls-ca
