export BASE = helm
export CHART = cert-manager
export NAMESPACE = cert-manager
export REPO = jetstack
export URL = https://charts.jetstack.io
export VERSION = 1.9.1

include ../Makefile

seal:
_PHONY: seal
