
export BASE = helm
export CHART = nginx-ingress
export NAMESPACE = ingress-nginx
export REPO = nginx-stable
export URL = https://helm.nginx.com/stable
export VERSION = 0.14.0

include ../Makefile

seal:
_PHONY: seal
