
export BASE = helm
export CHART = prometheus
export NAMESPACE = monitoring
export REPO = prometheus
export URL = https://prometheus-community.github.io/helm-charts
export VERSION = 15.10.4

include ../Makefile

seal:
_PHONY: seal
