apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app.kubernetes.io/name: metrics-server
  name: metrics-server
  namespace: kube-system

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server

  template:
    spec:
      containers:
        - args:
            - --cert-dir=/tmp
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --kubelet-use-node-status-port
            - --metric-resolution=15s
            - --secure-port=4443
          name: metrics-server
