
export BASE = helm
export CHART = mlflow
export NAMESPACE = mlflow
export REPO = deliveryhero
export URL = https://charts.deliveryhero.io/
export VERSION = 1.0.8

include ../Makefile

seal:
_PHONY: seal
