
export BASE = helm
export CHART = seldon-core-operator
export NAMESPACE = seldon-core-operator
export REPO = seldon-core
export URL = https://storage.googleapis.com/seldon-charts
export VERSION = 1.14.0

include ../Makefile

seal:
_PHONY: seal
