
export BASE = helm
export CHART = promtail
export NAMESPACE = monitoring
export REPO = grafana
export URL = https://grafana.github.io/helm-charts
export VERSION = 6.3.0

include ../Makefile

seal:
_PHONY: seal
