
export BASE = helm
export CHART = minio
export NAMESPACE = minio
export REPO = minio
export URL = https://helm.min.io/
export VERSION = 8.0.10

include ../Makefile

# preinstall:
# 	-kubectl create ns $(NAMESPACE)
# 	kubectl apply -f pv.yaml --namespace $(NAMESPACE)
# _PHONY: preinstall

seal:
_PHONY: seal
