
export BASE = helm
export CHART = redis
export NAMESPACE = redis
export REPO = bitnami
export URL = https://charts.bitnami.com/bitnami
export VERSION = 16.12.2

include ../Makefile

seal:
_PHONY: seal
