apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-vars
  namespace: "keycloak"
  labels:
    app.kubernetes.io/name: keycloak
data:
  KEYCLOAK_ADMIN: "root"
  KEYCLOAK_DATABASE_HOST: "postgresql.postgresql.svc.cluster.local"
  KEYCLOAK_DATABASE_PORT: "5432"
  KEYCLOAK_DATABASE_NAME: "keycloak"
  KEYCLOAK_DATABASE_USER: "keycloak"
