apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgBT+3KPzEAV7YQQfNc477P8LTiIx57tweZ3Z6ZitgxPiUOdLIrXtJLiHNH9l+JsnYAgHX0MA8aRwF0U6n8VsFLpocgbMYn5Ts1YWTih/Ko5199a+u4GJXKaNNh0Kiyn9H5WS/L04DD8QA2E3v0OBS+1abEA6Vk9xEKMXtezyg0mOPW8bZRKlY7SLbNADG+ETcvQjQ1AfWd/owxy15kJhJKKnY6FiBbhbsslInF6jsEkZgSUK0olrCChWkOpXO+rojbA5wlhsQGODvuCKSQb2RfULBSapp+PsrmTe2QOS3heXGnSzPcirMHLeocug70b0+VIRgo6PDvNAs7PzE3ZPTpZ1jFAUb274ks6JLwiGI+UjwR3QFxjeP18OjqwqGzHPwLm2H3nwsTwhymSWoBO9I66jG6KPAVYLXS6m0p9At8VKA5XKJWbygR5XZ4WE05oP1KNAxpHQS0vuHd9Zs1a3cSCXUAMc/Bc0v8RRiuIXsY4mlZXF5PtYhaRTGN6Q4GlQ1u2a+y5GhyACOFXMfxtmh06kG4br0z6jb5znGF7GtSl+hMFBtXZNO+4D6/GZKKiZxZ/3TqNphSXDrUdRT/NkpSITCMeZJ7Cdpz6fzIhEP6i2N8owdttbHO7+PNM1ngYsA9zsKwP9RBw0eQgN3yAg34JPBRTltpo8f4379avjNBe0JixyzwbBMb7BxPeQ7yduUTyy90TRTkWYA==
    password: AgCF4SHZxYi2YpsXNmwk/Yj40/+Y/EiQUj0FrTKXxzGAXpCH9nGR76cTNoqDv/v+4P8ELLFuE/0r+j6cPQHg4ysd9ZrWEClkpBY9qzByN0jzApGEZmWuCS/qXHL9n3B21Dq2rkhYinL2IQXkjom5jUJSK4XabsUN2HCFEAX7c0YZ/3NTX9x65+QkYwvYQ+Yv4Z0IXVDRdP/kJEnkMQmc04akVmMikdVCClRGSXXkUgtti++gBwm09vMVOS9Alu8RrfvMrUVXGIEyuKueM1ib3Ktj7Lyt4mKyibFNlq59O9bgbqO21pK/9YJZhQgsButC8MustzJjwwAZNIqRnXlIlE3+6vmv6Ioph04+dBg136QZxsjZAgPGInnyRlMTgDxFdN75fzg+9bMJdg1zA/E67fxPzWY8yupvRJPMjTXGJI3ZS9a6/R4xrSy3PHY5luucHwweKV5hVVTuog1h6Y2ENTvlPpG+AjI1cf+70MDjVghhFkVtrbX90RftsIMwFMKYqilpQ9FSz34FsFPvcwQSWX3T7dvBWO6asO0HYF8JQREumUJb7kOdz6eYS1l/mQ69mroHDB5UoHCUq4p1F8C7u7DPBeu5hYSiGRttvASPUPEhADfqofYymXyYd3aNKVqvlI3aDj/SMGbjjXzZtE5iafN8/DwNx1FkEmP02C+npCB4FB7EFcJ6wzJ2eX0/qWPCVzaF2jt4NJEtRQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak
      namespace: keycloak

