apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = true
    oauth_auto_login = true
    [auth.generic_oauth]
    allow_sign_up = true
    api_url = https://keycloak.lo/realms/master/protocol/openid-connect/userinfo
    auth_url = https://keycloak.lo/realms/master/protocol/openid-connect/auth
    client_id = grafana
    client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    enabled = true
    name = Keycloak
    role_attribute_path = contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
    scopes = profile,email,groups
    token_url = https://keycloak.lo/realms/master/protocol/openid-connect/token
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain =
    root_url = https://grafana.lo

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
