
export BASE = helm
export CHART = loki
export NAMESPACE = monitoring
export REPO = grafana
export URL = https://grafana.github.io/helm-charts
export VERSION = 3.0.0

include ../Makefile

seal:
_PHONY: seal
