
export BASE = helm
export CHART = kafka
export NAMESPACE = kafka
export REPO = bitnami
export URL = https://charts.bitnami.com/bitnami
export VERSION = 18.0.0

include ../Makefile

seal:
_PHONY: seal
